---
- name: Create directory for easy-rsa
  file:
    path: /etc/ssl/easy-rsa
    state: directory
    mode: 0755

- name: Get EasyRSA 3.0.7 from github
  unarchive:
    src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.7/EasyRSA-3.0.7.tgz
    dest: /etc/ssl/easy-rsa
    remote_src: yes
    validate_certs: False
    extra_opts: [--strip-components=1]

    