---
- name: "Include: Create users and groups"
  import_playbook: 10_users_groups.yml

- name: Install KNXD
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    chmod_files:
      ["/etc/default/eibd"
      ]

  tasks:
  - name: Create deb-files directory
    file:
      path: /etc/deb-files/
      state: directory
      mode: 0755

  - name: Copy eibd deb
    copy:
      src: packages/eibd_0.0.5-1_armhf.deb
      dest: /etc/deb-files/

  - name: Copy pthsem deb
    copy:
      src: packages/pthsem_2.0.8-1_armhf.deb
      dest: /etc/deb-files/

  - name: Copy eibdscript
    copy:
      src: executables/eibd.sh
      dest: /etc/init.d/eibd
      mode: 0755

  - name: Create eibd User
    user:
      name: eibd
      shell: /usr/sbin/nologin
      groups: users

  - name: eibdconf
    lineinfile:
      path: /etc/ld.so.conf.d/bcusdk.conf
      create: yes
      line: '/usr/local/lib'

  - name: Copy eibd conf
    copy:
      src: configs/eibd.ini
      dest: /etc/default/eibd

  - name: eibdlog
    lineinfile:
      path: /var/log/eibd.log
      create: yes
      line: 'EIBD Log'
      mode: 0777

  - name: Change permissions for configuration files
    file:
      path: "{{ item }}"
      group: smarthome
      mode: 0664
      state: file
    with_items: "{{ chmod_files }}"


  # sudo dpkg -i /etc/deb-files/pthsem_2.0.8-1_armhf.deb
  # sudo dpkg -i /etc/deb-files/eibd_0.0.5-1_armhf.deb
  # sudo ldconfig
  # sudo update-rc.d eibd defaults
  # sudo systemctl start eibd
  # sudo systemctl enable eibd
  # sudo systemctl disable knxd.service &> /dev/null
  # sudo systemctl disable knxd.socket &> /dev/null
