---
- name: "Include: Create users and groups"
  import_playbook: 20_users_groups.yml

- name: "Include: Install PHP"
  import_playbook: 04_php_install.yml

- name: Install smartVISU
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    branch: master
    htmlpath: /var/www/html
    smartvisudir: smartvisu

  tasks:
  - name: "Git smartVISU ({{branch}})"
    git:
      repo: 'https://github.com/Martin-Gleiss/smartvisu'
      dest: "{{ htmlpath }}/{{ smartvisudir }}"
      version: "{{ branch }}"
      force: yes
    register: git
  - debug: var=git

  - name: Change Owner of smartVISU installation
    file:
      path: "{{ htmlpath }}/{{ smartvisudir }}"
      owner: smarthome
      group: www-data
      mode: u=rwX,g=rwX,o=rX
      recurse: yes
      state: directory

  # - name: Restart nginx
  #   systemd: state=restarted name=nginx

