- name: update and upgade Linux distribution
  hosts: all
  become: true
  become_user: root

  tasks:
  - name: set timezone to Central Europe
    timezone:
      name: Europe/Berlin

  - name: install locale
    locale_gen:
      name: de_DE.UTF-8
      state: present

  - name: install english locale
    locale_gen:
      name: en_GB.UTF-8
      state: present

  - name: Set locale
    command: 'update-locale LANG=de_DE.UTF-8'
    register: locale
  - debug: var=locale

# change until reboot:
# set hostname to SmartHomeNG (default is raspberrypi)
# set hostname in /etc/hosts too - Change '127.0.1.1		raspberrypi' to '127.0.1.1		SmartHomeNG'

# Change permanently:
# sudo hostnamectl set-hostname shNG

# sed "s/raspberrypi/SmartHomeNG/" /etc/hosts>/etc/hosts2
# mv /etc/hosts2 /etc/hosts

