---
- name: Install Apache webserver
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Populate service facts
    service_facts:

  - name: Stop and disable NGINX
    systemd:
      name: nginx 
      state: stopped
      enabled: no
    when:
    - ansible_facts.services['nginx.service'] is defined

  - name: Install apache2
    apt:
      name: apache2
      state: latest

  - name: Rename example index.html
    command: mv /var/www/html/index.html index.apache.html

  - name: Create an empty index.html
    file:
      path: "/var/www/html/index.html"
      state: touch

  - name: Test if PHP is installed
    command: php -v
    register: myoutput
    ignore_errors: yes

  - name: Update PHP installation, if PHP is installed
    import_tasks: tasks/php_install_tasks.yml
    when: myoutput['rc'] == 0
