---
- name: "Include: Create users and groups"
  import_playbook: xx_users_groups.yml

- name: Install Samba
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    samba_users:
      - name: smarthome
        password: smarthome

  tasks:
  - name: Install Samba
    apt: 
      name; samba
      force: no
      state: latest

  - name: Save original Samba config file
    copy:
      dest: /etc/samba/smb.conf.bak
      src: /etc/samba/smb.conf

  - name: Copy Samba config
    copy:
      dest: /etc/samba/smb.conf
      src: configs/samba.conf
      owner: smarthome
      group: smarthome
      mode: 0664

# ------

  # - name: Create Samba users
  #   shell: >
  #     (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
  #     || (echo {{ item.password }}; echo {{ item.password }}) \
  #     | smbpasswd -s -a {{ item.name }}
  #   with_items: "{{ samba_users }}"
  #   register: create_user_output
  #   changed_when: "'Added user' in create_user_output.stdout"

  # - name: create systemd dir smb
  #   file:
  #     path: /etc/systemd/system/smbd.service.d/
  #     state: directory

  # - name: Copy service_conf smb
  #   copy:
  #     src: configs/service_smbd_fix.conf
  #     dest: /etc/systemd/system/smbd.service.d/
  #     owner: smarthome
  #     group: smarthome
  #     mode: 0644

  # - name: create systemd dir nmb
  #   file:
  #     path: /etc/systemd/system/nmbd.service.d/
  #     state: directory

  # - name: Copy service_conf nmb
  #   copy:
  #     src: configs/service_nmbd_fix.conf
  #     dest: /etc/systemd/system/nmbd.service.d/
  #     owner: smarthome
  #     group: smarthome
  #     mode: 0644

  # - name: Restart smbd
  #   systemd: state=restarted name=smbd
  #   notify: Enable smbd

  # handlers:
  #   - name: Enable smbd
  #     systemd: enabled=yes name=smbd
