- name: Install needed packages Raspberry Pi
  hosts: all
  become: true
  become_user: root

  tasks:
  #  Install for numpy on Raspberry Pi
  - name: Install libatlas-base-dev (needed for numpy installation)
    apt:
      name: libatlas-base-dev
      state: latest

