---
- name: Install SmarthomeNG
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    branch: master

#  vars:
#    apt_install:
#      ["dialog",
#      "rlwrap",
#      "libyaml-dev",
#      "graphviz",
#      "rrdtool",
#      "librrd-dev"
#      ]

  tasks:
  - name: "Include: Create users and groups"
    import_tasks: xx_users_groups_tasks.yml

#  - name: install apt
#    apt:
#      name: "{{ item }}"
#      state: latest
#      autoremove: yes
#      autoclean: yes
#    with_items: "{{ apt_install }}"

  - name: "Git SmarthomeNG ({{branch}})"
    git:
      repo: 'git://github.com/smarthomeNG/smarthome.git'
      dest: /usr/local/smarthome
      version: "{{ branch }}"
      force: yes
    register: git
  - debug: var=git

  - name: "Git Plugins ({{branch}})"
    git:
      repo: 'git://github.com/smarthomeNG/plugins.git'
      dest: /usr/local/smarthome/plugins
      version: "{{ branch }}"
      force: yes
    register: git2
    ignore_errors: yes
  - debug: var=git2

  - name: Change Owner of SmartHomeNG installation
    file:
      path: /usr/local/smarthome
      owner: smarthome
      group: smarthome
      mode: u=rwX,g=rwX,o=rX
      recurse: yes
      state: directory


  - name: Copy Service
    copy:
      dest: /lib/systemd/system/smarthome.service
      src: config_files/smarthome.service

  - name: Change Owner of service definition
    file:
      path: /lib/systemd/system/smarthome.service
      group: smarthome
      mode: 0664
      state: file

#  - name: plugins ignore perm
#    command: git config core.fileMode false chdir=/usr/local/smarthome/plugins

#  - name: sh ignore perm
#    command: git config core.fileMode false chdir=/usr/local/smarthome/

#  - name: Remove astral
#    pip: name=astral executable=pip3 state=absent

#  - name: List Modules
#    command: "su smarthome -c 'yolk --list'"
#    register: pip3
#    ignore_errors: yes
#    become: true
#    become_user: smarthome
#  - debug: var=pip3
