---
- name: "Include: Create users and groups"
  import_playbook: xx_users_groups.yml

- name: Install KNXD
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    chmod_files:
      ["/lib/systemd/system/knxd.service",
      "/lib/systemd/system/knxd.socket",
      "/etc/knxd.conf",
      "/etc/knxd.ini"
      ]

  tasks:
  - name: Install knxd
    apt:
      name: knxd
      state: latest

  - name: Install knxdtools
    apt:
      name: knxd-tools
      state: latest

  - name: Copy knxd.conf (with an example)
    copy:
      dest: /etc/knxd.conf
      src: configs/knxd.conf

  - name: Copy knxd.ini (an example)
    copy:
      dest: /etc/knxd.ini
      src: configs/knxd.ini

  - name: Change permissions for configuration files
    file:
      path: "{{ item }}"
      group: smarthome
      mode: 0664
      state: file
    with_items: "{{ chmod_files }}"
