---
- name: Install 1-wire support owserver
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    chmod_files:
      ["/lib/systemd/system/owhttpd.service",
      "/lib/systemd/system/owserver.service",
      "/lib/systemd/system/owserver.socket",
      "/etc/owfs.conf"
      ]

  tasks:
  - import_tasks: tasks/users_groups_tasks.yml

  - name: Install 1-wire support
    apt:
      name: 
      - owhttpd
      - owserver
      state: latest
    ignore_errors: yes

  - name: Change permissions for configuration files
    file:
      path: "{{ item }}"
      group: smarthome
      mode: 0664
      state: file
    with_items: "{{ chmod_files }}"
