---
- name: Install PHP
  hosts: all
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Install php
    apt:
      name: php
      state: latest

  - name: Install php7.3-fpm
    apt:
      name: php7.3-fpm
      state: present

  - name: Install php-mbstring
    apt: 
      name: php-mbstring
      force: no
      state: latest

  # - name: xml
  #   apt: name=php7.3-xml force=no state=latest

  # - name: Restart php
  #   systemd: state=restarted name=php7.3-fpm.service



  - name: create phpinfo
    blockinfile:
      mode: 0644
      owner: www-data
      group: www-data
      create: yes
      path: /var/www/html/phpinfo.php
      block: |
        <?php
        // Show all information, defaults to INFO_ALL
        phpinfo();
        ?>



  - name: Populate service facts
    service_facts:

  - name: Restart apache2
    systemd: 
      state: restarted
      name: apache2.service
    when:
    - ansible_facts.services['apache2.service'] is defined
    - ansible_facts.services["apache2"]["state"] == "running"

  - name: Restart nginx
    systemd:
      state: restarted
      name: nginx.service
    when:
    - ansible_facts.services['nginx.service'] is defined
    - ansible_facts.services["nginx"]["state"] == "running"

